### PR TITLE
Ensure public assets served from the same domain are opened in a new tab

### LINKED ISSUE #485: Link to Utsläppsberäkningar report is broken
Even though the URL seems correct, the link to the Utsläppsberäkningar report (link at bottom of https://www.klimatkollen.se/utslappsberakningar)

Screenshot 2024-05-02 at 08 32 48

yeilds a 404ish page (no 404 text, "Gå till startsidan" at top of screen).

Screenshot 2024-05-02 at 08 33 00

When reloaded, correct pdf is displayed (https://www.klimatkollen.se/utslappsberakningar.pdf).

### PR DESCRIPTION
**Pull request by Greenheart**
fixes #485 

This affected all internal links to PDFs hosted on the same origin as the Next.js app. This was introduced together with the i18n refactoring, and not caught due to the habit of manually CTRL-clicking links when testing.

This PR also improved the layout for the 404 page.

### CODE REVIEW

**Comment by LudwikJaniuk** [comment]
How come the fix involves new-tab opening?

**Comment by Greenheart** [comment]
Good question. When using the Next.js [Link](https://nextjs.org/docs/pages/api-reference/components/link) component, all links to the same origin (e.g. relative URLs starting with `/`) are treated as if they are part of the app, which triggers data preloading.

While we do want prefetching for some links in markdown content, our PDFs should be treated as external links (to prevent the 404 caused by failed data preloading).

This is a bit clunky, compared to how a similar framework SvelteKit has solved this exact issue: https://kit.svelte.dev/docs/link-options. But this Next.js solution seems to work well enough for our use case.

**Comment by LudwikJaniuk** [comment]
Okay, if it's what's needed to solve it, so be it.

**Review by elvbom — APPROVED** [review]
Bra jobbat!

**Pull request merged**
