### PR TITLE
Brush up readme

### PR DESCRIPTION
**Pull request by LudwikJaniuk**
Cleaned up readme, reorganized some sections and added better advice on contributing.

### CODE REVIEW

**Comment by LudwikJaniuk** [comment]
Will merge on monday if no objections

**Comment by Sparky338** [comment]
@LudwikJaniuk No objections, but possibly a clarification on how to contribute. For example, being more clear about the specific process of contributing changes, needing to fork the repo and creating a PR after completing the work. Might be a little excessive, but it can be helpful for folks new to open source projects.

**Comment by LudwikJaniuk** [comment]
That's next on my to-do list @Sparky338 !

**Review by elvbom — APPROVED** [review]
Snyggt jobbat!

**Pull request merged**
