### PR TITLE
Fixes #463

### LINKED ISSUE #463: Consider removing the unneeded Borna font assets from the `public` directory
For example, the demo pages are published to the live webpage. Maybe move this to another directory, and only preserve the actual font files we need in the public directory, since this would make our deployments smaller and more focused.

https://www.klimatkollen.se/fonts/Borna/webfontkit/borna-bold-demo.html

### PR DESCRIPTION
**Pull request by N-Asadnajafi**
Removed the unneeded Borna font assets from the public directory. Please see the differences in the main product and in my local in this picture:
Screenshot 2024-05-15 at 16 01 45

### CODE REVIEW

**Comment by LudwikJaniuk** [comment]
This changes how the page looks. I'm not sure it's "unneeded" then (quoting https://github.com/Klimatbyran/klimatkollen/issues/463). @Greenheart given that we're moving to a new typeface for klimatkollen, please weigh on which font is the one to be used going forward.

**Comment by Greenheart** [comment]
Thanks for taking a look at this Narges!

I gave unclear instructions in #463, and like Ludvig mentioned I should have defined what I meant with "unneeded Borna font assets". Going forward, I will try to add more context to issues to define the goals with each update we want to make. And please let me know if anything needs to be clarified :)

For #463, what I had in mind was to remove the testing files (primarily the html files) from `public/fonts/Borna/webfontkit/**/*.html`.

I'm updating the all fonts and colors as part of #590, but until then we should keep the website look intact. Thus, I will make changes to this PR so it's ready to merge, and then continue in my other branch with updating the font and colors.

---


## Finally, a side note:
@LudwikJaniuk Perhaps we should also look into creating an GitHub issue template, to automatically get a good structure when we create issues. Here's some inspiration: https://github.com/29ki/29k/tree/main/.github/ISSUE_TEMPLATE 

Most importantly, we need a clear definition of "done" for each issue, to make it easier to understand the evaluation criteria to get a PR merged.

**Review by Greenheart — APPROVED** [review]
Verified fix for #463

Thanks for initiating this! :)

**Comment by LudwikJaniuk** [comment]
Agreed on the side note. I'll look into it.

**Pull request merged**
