### PR TITLE
Fix 347 add sitemap and robots.txt

### LINKED ISSUE #347: Add sitemap and robots.txt

### PR DESCRIPTION
**Pull request by Braggedtooth**
resolves #347

### CODE REVIEW

**Comment by LudwikJaniuk** [comment]
If you run `npm run lint`, that will probably say why the bot is unhappy.

**Comment by Braggedtooth** [comment]
@LudwikJaniuk fixed

**Comment by LudwikJaniuk** [comment]
@Braggedtooth Nice! @elvbom will do the final review as soon as possible.

**Review by elvbom — APPROVED** [review]

**Comment by elvbom** [comment]
Bra jobbat!!

**Pull request merged**
