### PR TITLE
Update carbon budget links after code base update

### PR DESCRIPTION
**Pull request by Sparky338**
Updated the links to the 2022 documentation to reflect the given link in Issue https://github.com/Klimatbyran/klimatkollen/issues/468. Found two other references to the same documentation and updated them as well. Previous link to the 2022 documentation is preserved in each case as a separate link noting that it is an older document. There is a deviation to this on the "Partierna" page, as I was unsure if the way it is calculated on the website was updated to the new documentation. 

This is a correction to PR https://github.com/Klimatbyran/klimatkollen/pull/470 as there was a major code base change that negated the updates.

### CODE REVIEW

**Comment by LudwikJaniuk** [comment]
Thanks for you contribution and sorry for the delay in review. I've made minor modifications. I think it's good to keep the small text brief, but left the reference to the other version of the document in the longer text.

**Comment by LudwikJaniuk** [comment]
@elvbom Since it's a minor change, I merged directly.

**Comment by LudwikJaniuk** [comment]
@Sparky338 Feel free to join the discord (see README) or message me if you would like guidance on further contributions. Thanks for your help!

**Comment by Sparky338** [comment]
@LudwikJaniuk You're welcome! And no worries about the delay. I trust your modifications, especially since I don't know the Swedish language and the overarching content of the pages.

**Pull request merged**
