### PR TITLE
add all numeric columns to historical emissions

### PR DESCRIPTION
**Pull request by elvbom**
Add all numeric columns to historical emissions in climate data calculations so that this doesn't need to be hardcoded with future updates from SMHI.

### CODE REVIEW

**Review by Greenheart — APPROVED** [review]
This works well, and is for sure more Pythonic! :snake:

**Review by Greenheart — CHANGES_REQUESTED** [review]
Actually, wait a minute. Something changed in my `climate-data.json` output.

I get a `NaN` value in the output, which is not valid JSON.

Investigating what happened.

**Review by Greenheart — APPROVED** [review]
Now approving this after clarifying with Elvira that the data changes are expected since this version of the data processing assumes the latest SMHI data version (which was 2021 when this PR was submitted and 2022 was just published before I tested this).

This will be updated in upcoming PRs.

**Comment by elvbom** [comment]
> Actually, wait a minute. Something changed in my `climate-data.json` output.
> 
> I get a `NaN` value in the output, which is not valid JSON.
> 
> Investigating what happened.
> ## Details:
> 
> Kumla kommun gets `"neededEmissionChangePercent": NaN`. This feels familiar, maybe you solved this last week in another branch @elvbom?

Yes, this is because of SMHI emissions data being updated with entries for 2022. It's adressed in #583

**Pull request merged**
