### PR TITLE
Feature/klimatkollen add sorting to binary data

### PR DESCRIPTION
**Pull request by clalil**
Related to: https://github.com/Klimatbyran/klimatkollen/issues/351

This PR modifies the code so that the sorting is based on municipality: i.e. if the user sorts for "has action plan", the answer "yes/no" is still alphabetically sorted. The PR also initialises the column data in alphabetical order for the municipalities based on which municipalities currently have an action plan.

image
image

### CODE REVIEW

**Comment by LudwikJaniuk** [comment]
Thanks for this contrbution. As I'm testing it, I still seem to see some issues. If I press "Kommun", it still primarily sorts on "har plan" and only then on "Kommun". I think if someone presses "kommun" that should be the main sort. Could you take a look if that is what you intended?

I'm happy to help out with how to move forward and do more review. Ping me either here or on Discord if I forget to reply :)

**Comment by clalil** [comment]
@LudwikJaniuk Thank you so much for the feedback! That is a completely valid point - I think I completely missed that just focusing on the sorting of the "action plans". I've never used TanStack before, and only have time to put into this during weekends. If anyone solves it before me they're more than welcome to - I'm happy to learn things regardless. :)

**Comment by LudwikJaniuk** [comment]
No worries - it's important to test your changes, but the review process is also here to help you. This is not a critical change so don't worry about taking the time you need - assuming of course you're still interested in resolving this and it is fun for you. Again, if you need help, reach out on Discord.

**Comment by LudwikJaniuk** [comment]
@clalil Please let us know if you still want to work on this bug. If not, someone else could take over.

**Comment by clalil** [comment]
> @clalil Please let us know if you still want to work on this bug. If not, someone else could take over.

Hi Ludvig! Sorry, like I mentioned before I do have limited time to work on it. So far, looking at the docs & TanStacks's own sandbox example, I can't seem to find a fix that achieves the desired outcome after trying a couple of different approaches. Since I have a lot on my plate at the moment, and still haven't made sense of it, it is better if someone else grabs it that can give it full attention without further delays so that the issue can be resolved I think. 

Apologies for the delays. 🙏

**Comment by LudwikJaniuk** [comment]
@clalil no worries, and thanks for letting us know. If your outlook changes in the future, welcome back!

**Pull request closed without merging**
