### PR TITLE
#396 add mobile device map tooltips on tap

### PR DESCRIPTION
**Pull request by datalowe**
Issue: https://github.com/Klimatbyran/klimatkollen/issues/396

**Main updates**
- Tapping screen on mobile device triggers a tooltip
- Tapping the tooltip itself sends user to detailed municipality view
   - There is currently no clear visual indicator to the user that the tooltip is a link. Please give input on how to handle this - e.g. should the tooltip as a whole continue being a link, but with a text saying "Click for more info"? Or should say the "Click for more info" text be turned into a link (while the rest of the tooltip isn't one)?
- If the user first taps one municipality and then somewhere else, the former tooltip is removed (clicking where there is no municipality makes the tooltip disappear entirely).
- Logic has been added to prevent users on desktop from being shown these 'mobile tooltips'
   - There is one edge case where a desktop user could briefly be shown a mobile tooltip. If they go to the main page, with their browser set to a <769 px width, and have the cursor already placed on the map (ie they do not move the mouse), and click, the mobile tooltip will be shown until they move their cursor. I couldn't think of a reasonable way to prevent this, and it seems like a very small problem.

スクリーンショット 2024-03-16 16 57 55

**Auxiliary updates**
- Desktop users must now move their cursor/hover somewhere before they can click on a municipality. This was essentially a side effect of the logic I wrote for mobile/tablet devices, but it seems like desired behavior to me anyway.
- I replaced magic value references to mobile device width with references to numeric values in `devices.ts`.
- In "components/Map/Map.tsx", I renamed `municipalityData` to `municipalityFeatureCollection` since the former name was confusing, due to `municipalityData` having completely different properties than the `MunicipalityData` type.
- I added a [type guard](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) for MunicipalityData to clean up and clarify (remove eg `as unknown as MunicipalityData`) related code in Map.tsx.
- I moved all "components/Map/Map.tsx" types to "utils/types.ts". I don't know if this is their right home, but they should be in a separate file IMO since Map.tsx was getting unwieldy.

This is my first PR, meaning I'm not very familiar with the repo's style, so if you disagree with any of the changes I made I'd be happy to see them reverted :)

Oh and please note that I have not tested the PR on an actual mobile device, only through dev tools on desktop.

### CODE REVIEW

**Comment by datalowe** [comment]
Looking at the preview on my phone reminded me that we also want the tooltips to be cleared whenever the user zooms in/out or pans around. I'm guessing that this is solvable, but might add some complexity... I'll have a look, but maybe someone can think of a cleaner approach than me.

**Review by allazis — CHANGES_REQUESTED** [review]
Good find! I agree that it is not optimal that the first tap on the mobile map sends you directly to the page for the municipality.

Have tested your PR in Android and iPhone and received the following test results:

With a short tap, the tooltip with the municipality name flickers quickly and then you are still sent to the municipality page.
With a long tap, the tooltip with the municipality name is displayed without one being forwarded to the municipality page. However, sometimes the tooltip just flickers and doesn't stay.
It flickers slightly less in iPhone than in Android. Recommend you adjust your PR so it works as intended and test the changes on the phone. Desktop tests alone don't seem to be enough for this one.

You will find the link to the latest deployment based on the PR here in the thread. Login to GitHub from your phone and you can reach it from there.

**Comment by datalowe** [comment]
> Good find! I agree that it is not optimal that the first tap on the mobile map sends you directly to the page for the municipality.
> 
> Have tested your PR in Android and iPhone and received the following test results:
> 
> With a short tap, the tooltip with the municipality name flickers quickly and then you are still sent to the municipality page. With a long tap, the tooltip with the municipality name is displayed without one being forwarded to the municipality page. However, sometimes the tooltip just flickers and doesn't stay. It flickers slightly less in iPhone than in Android. Recommend you adjust your PR so it works as intended and test the changes on the phone. Desktop tests alone don't seem to be enough for this one.
> 
> You will find the link to the latest deployment based on the PR here in the thread. Login to GitHub from your phone and you can reach it from there.

Great that you find this, I'll have to see what's going on then. I did test on my cell phone once the preview became available, but on my phone it worked without any apparent issues. Maybe I need to play around with it more, or perhaps it's model-dependent.

**Comment by datalowe** [comment]
I improved the touch device detection/handling, and the behavior is now as expected on Firefox and Chrome, both on the newish and older phone that I've used for testing. Desktop usage is still unaffected by the updates. Could you check if things work on your end too now @allazis?

I've used interaction media features to detect touch devices, which should be supported on all major modern browsers https://caniuse.com/?search=media%20features If someone would use a really old browser or for some other reason not have their touch device being identified as such, the behavior will just be the same as it used to be before this PR.

Again, it would probably be best if there was a design discussion on how the tooltip link should work before this PR is merged, as I mentioned in the opening comment.

**Comment by allazis** [comment]
@datalowe Great! 

After testing on iPhone and Android I can confirm the functionality: 

1. For users with mobile devices the tooltip will appear when tapping a municipality in the map. No flickering. 
2. When the tooltip is tapped one gets to the corresponding municipality page. 
3. Tapping a different municipality within the map while a tooltip is visible, the first tooltip disappears and the tapped municipality's tooltip appear.
4. Tapping within the map but outside the country's border makes a visible tooltip disappear.

Would like the same behaviour as in point 4 but for when tapping anywhere on the page. That is, the tooltip should also disappear if you click above or under the map. Do you agree and can you fix this? 

As you mentioned, this design should be discussed before merging. When things are ready, I will let others on Klimatkollen test the new behaviour too :)

**Comment by datalowe** [comment]
> Would like the same behaviour as in point 4 but for when tapping anywhere on the page. That is, the tooltip should also disappear if you click above or under the map. Do you agree and can you fix this?

Sure, that makes sense. I found [this approach on SO](https://stackoverflow.com/a/42234988), using a React hook, to achieve the behavior you describe. It appears to work on my phone, but please check if it works for you too :)

**Review by allazis — APPROVED** [review]
Works as intended!

Will ask others at Klimatkollen to test before merging.

**Comment by datalowe** [comment]
Synced & merged with staging.

**Comment by LudwikJaniuk** [comment]
Just adding some testing of my own. 
What I tested:
 * Tooltips show up
 * They take you to the municipality on second click
 * They disappear when you click elsewhere on the map
 * Or elsewhere on the page
 
 On browsers: 
  * Chrome / mobile mode
  * Edge / mobile mode
  * Firefox on my motorola edge
  * Chrome on my motorola edge
  
They all seem to work as advertised.
  
@allazis You tested on iOS right?
 
My two cents: If the text in the popup was underlined, that would make it clearer it's clickable.

**Comment by allazis** [comment]
@LudwikJaniuk yep, tested in Chrome on iPhone.

**Comment by LudwikJaniuk** [comment]
Thanks @allazis .

@datalowe is there any other testing remaining? How complete do you feel this PR is?

**Comment by datalowe** [comment]
I didn't have any more testing in mind, AFAIU what's being used should work on all reasonably recent versions of the major web browsers. It'd be great to have automated tests for this ofc, but I would probably need to work quite a bit on familiarizing myself with the the project's testing framework etc, and it might be a while before I'd be able to make enough time for that. So if you think this is enough I agree :)

Should I add styling to make the pop-up text underlined then, like you suggested?

**Comment by Greenheart** [comment]
Thanks Lowe - nice work! Several good improvements in here! :smile:

This sparked an interesting discussion around how we could make comparisons between municipalities easier. I will open an issue for further exploration.

Initially I wrote feedback for what to change before we could merge this, but halfway through I realised I had a very specific idea in mind and that it would be easier to just push a commit :sweat_smile: 

If the others approve the latest changes, this is now ready to merge. Thank you for your contribution! :raised_hands:

**Comment by LudwikJaniuk** [comment]
The (i) icon is a great complement to the underlining. I like this!

**Pull request merged**
