### PR TITLE
Social links update

### PR DESCRIPTION
**Pull request by Lasse2500**
Added link to Klimatkollen's profile on Instagram and Facebook. Issue: #471

### CODE REVIEW

**Comment by LudwikJaniuk** [comment]
Hi @Lasse2500,

When I run your code I get a 404 error - do you have any idea why that could be?

**Comment by LudwikJaniuk** [comment]
Hi again,
I believe this has nothing to do with your changes. I'm investigating the issue.

**Comment by LudwikJaniuk** [comment]
I got past the 404 issue by rebasing onto the latest changes on staging. Please do the same. (and feel free to ask for git help if needed).

As for the changes: the facebook icon is white, standing out against all the other black icons. It should follow the same existing style. Also, there is a change with the discord, can you explain the intention there? (since there is already a discord link on the page).

**Comment by LudwikJaniuk** [comment]
The white facebook icon is still there after the last update. If you fix it in the future, please comment. 
By the way, I remember @Greenheart we had a conversation about changing some library for the icons. Does that affect this PR in any way?

**Review by elvbom — APPROVED** [review]
Well done!

**Pull request merged**
